package com.ihcl.payment.util

object Constants {
    const val REUESTTIMEOUTMILLIS = 80000
    const val INTEGRATION = "iframe"
    const val ORDER_STATUS_CONTENT_TYPE = "application/x-www-form-urlencoded"
    const val ORDER_STATUS_VERSION_KEY = "version"
    const val CART_CUSTOMER_HASH = "CUSTOMERHASH"
    const val CUSTOMERHASH = "customerhash"

    //Juspay initiate api const values
    const val INITIATE_ACTION = "initiate"
    const val INITIATE_HYPERSDKDIV = "merchantViewId"
    const val INITIATE_SERVICE = "in.juspay.hyperpay"
    const val JUSPAY_SERVICE = "in.juspay.hyperpay"
    const val PAY_AT_HOTEL = "PAY AT HOTEL"
    const val TENANT = "tenant"
    const val FETCH_ACTION = "paymentPage"
    const val FETCH_LANGUAGE = "english"
    const val FETCH_ENTRYPOINT = "content"
    const val METADATA_JUSPAY_GATEWAY_REFERENCE_ID_HOTEL = "ONLINE"
    const val METADATA_JUSPAY_GATEWAY_REFERENCE_ID_GC = "TEGC"
    const val METADATA_JUSPAY_GATEWAY_REFERENCE_ID_EPICURE = "EPICURE"
    const val CARD_NAME = "card_name"
    const val TRACKING_ID = "tracking_id"
    const val SI_REF_NO = "si_ref_no"
    const val BANK_REF_NO = "bank_ref_no"
    const val PAYMENT_MODE = "payment_mode"
    const val TRANS_DATE = "trans_date"
    const val PENDING_VBV = "PENDING_VBV"
    const val ORDER_SUCCEEDED = "ORDER_SUCCEEDED"
    const val ORDER_FAILED = "ORDER_FAILED"
    const val TXN_CREATED = "TXN_CREATED"
    const val AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED"
    const val CHARGED = "CHARGED"
    const val PENDING = "PENDING"
    const val INITIATED = "INITIATED"
    const val FAILED = "FAILED"
    const val ABORTED = "Aborted"
    const val FAILURE_MESSAGE = "failure_message"
    const val SELF = "self"
    const val SOME_ONE_ELSE = "someOneElse"
    const val PHYSICAL_GC = "PGC"
    const val E_GC = "EGC"
    const val WEB = "WEB"
    const val FALSE = "false"
    const val PHYSICAL_GIFT_CARD = "physical_gift_card"
    const val GATEWAY="gateway"
    const val TAJ="taj"
    const val HEADER_ORIGIN="Origin"
    const val HEADER_TENANT="Tenant"
    //Refund API Constants
    const val REFUND = "/refunds"
    const val X_MERCHANTID = "x-merchantid"
    const val UNIQUE_REQUEST_ID = "unique_request_id"
    const val AMOUNT = "amount"

    //webhook API Constants
    const val JUS_PAY = "JUS_PAY"
    const val EVENT_NAME = "event_name"
    const val CONTENT = "content"
    const val ORDER = "order"
    const val ORDER_ID = "order_id"
    const val PAYMENT_GATEWAY_RESPONSE = "payment_gateway_response"
    const val GATEWAY_RESPONSE = "gateway_response"
    const val TXN_DETAILS = "txn_detail"
    const val TXN_ID = "txn_id"
    const val TXN_UUID = "txn_uuid"
    const val STATUS = "status"
    const val CREATED = "created"
    const val GATEWAY_ID = "gateway_id"
    const val WEBHOOK_PAYMENT_MODE = "payment_mode"
    const val WEBHOOK_PAYMENT_METHOD = "payment_method"

    //Status codes
    const val BAD_REQUEST = 400
}
