env:
  databaseName: "IHCLUATDataBase"
  connectionString: "mongodb://ihcluat:LbAgFmOKkyPZsHiMJO9yfDYDkyYKR5gsIqt8IKdU4HDQrtpsWRssDdRHIdrfEZLj2t9HuLPDGW3lACDbPGJtqw==@ihcluat.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@ihcluat"
  baseUrl: "https://sandbox.juspay.in/orders"
  filepath: "/app/bin/PrivateKey.pem"
  merchantId: "ihcl"
  client_id: "taj"
  gatewayClient_id: "gatewayhotels"
  merchantKeyId: "11111"
  workingKey: "97122C963A5968F55FBF2F1D157AC74D"
  gatewayWorkingKey : "0F52152467E9748A8F4D9E445F05F3E7"
  cartUrl: "http://ihcl-cartservice:8081/v1/cart/empty-cart"
  returnUrl: "https://web-uatv2.tajhotels.com"
  gatewayReturnUrl: "https://gateway-web-uat.tajhotels.com"
  orderStatusUrl: "?options.add_full_gateway_response=true"
  webhook_url: "https://api-uatv2.tajhotels.com/paymentService/v1/juspay/webhook"
  refundVersion: "2018-10-25"
  refundMerchantId: "merchant_id"
  confirmationVersion: "2021-08-21"
  authorization: "Basic QzAwMjIyMEJBM0U0NDk4QTBENTJEREEyRDFCRjE1Og=="
  processSDKService: "in.juspay.hyperpay"
  initiateEnvironment: "sandbox"
  requestTimeoutMillis: "120000"
  connectionPoolMinSize: 10
  connectionPoolMaxSize: 20
  APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=4754bffe-22da-4c66-b893-b426d8b63c5d;IngestionEndpoint=https://centralindia-0.in.applicationinsights.azure.com/;LiveEndpoint=https://centralindia.livediagnostics.monitor.azure.com/;ApplicationId=ee8f6d66-6882-4db2-b1cc-2a2929bb1184"
