  env:
   databaseName: "IHCLSITDataBase"
   connectionString : "mongodb://ihclsit:tmBXKavuBiNYle6GEdHoEIeVjprZN6dk7Hes4GBOoYu2Lguk7cQwXgkPAQM2HXiJ2uqOHD4LmsYWACDbgxGFyw==@ihclsit.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@ihclsit@"
   baseUrl: "https://sandbox.juspay.in/orders"
   filepath: "/app/bin/PrivateKey.pem"   
   merchantId: "ihcl"
   client_id: "taj"
   gatewayClient_id: "gatewayhotels"
   merchantKeyId: "11111"
   workingKey: "97122C963A5968F55FBF2F1D157AC74D"
   gatewayWorkingKey : "8BC8F435DA6F234C55F5E8F871BF2F43"
   cartUrl: "http://ihcl-cartservice:8081/v1/cart/empty-cart"
   returnUrl: "https://web-qa1v2.tajhotels.com"
   gatewayReturnUrl: "https://gateway-web-qa1v2.tajhotels.com"
   orderStatusUrl: "?options.add_full_gateway_response=true"
   webhook_url: "https://api-qa1v2.tajhotels.com/paymentService/v1/juspay/webhook"
   refundVersion: "2018-10-25"
   refundMerchantId: "merchant_id"
   confirmationVersion: "2021-08-21"
   authorization: "Basic QzAwMjIyMEJBM0U0NDk4QTBENTJEREEyRDFCRjE1Og=="
   processSDKService: "in.juspay.hyperpay"
   initiateEnvironment: "sandbox"
   requestTimeoutMillis: "120000"
   connectionPoolMinSize: 10
   connectionPoolMaxSize: 20
